
import { Analytics } from '@vercel/analytics/react';

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from '@/components/Footer';
import { about,gallery,events,sponsors,faq } from './page';
import Navbar from '@/components/navbar';

const font = Poppins(
  { subsets: ["latin"],
    weight: '400'
}
  );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      suppressHydrationWarning={true}
      className={font.className}>
        <Analytics />
        <Navbar
        scrollToAbout={about}
        scrollToEvents={events}
        scrollToGallery={gallery}
        scrollToBrands={sponsors}
        scrollToInfo={faq}
        />
        {children}
        <Footer />
        </body>
    </html>
  );
}
